// Code generated by "stringer -type=relationship"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Less-1]
	_ = x[LessEqual-2]
	_ = x[Equal-3]
	_ = x[GreaterEqual-4]
	_ = x[Greater-5]
	_ = x[Colon-6]
}

const _relationship_name = "InvalidLessLessEqualEqualGreaterEqualGreaterColon"

var _relationship_index = [...]uint8{0, 7, 11, 20, 25, 37, 44, 49}

func (i relationship) String() string {
	if i < 0 || i >= relationship(len(_relationship_index)-1) {
		return "relationship(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _relationship_name[_relationship_index[i]:_relationship_index[i+1]]
}
